services:
  tools:
    build: .
    depends_on:
      - ldap
    stdin_open: true # docker run -i
    tty: true # docker run -t
  ldap:
    build: ../docker/
    environment:
      - SLAPD_LOG_LEVEL=-1
      - BIND_PASSWORD=password
      - LOCAL=true
      - LDAP_HOST=0.0.0.0
      - LDAP_PORT=389
    ports:
      - "389:389/tcp"
      - "389:389/udp"
    volumes:
      - ../docker/mdb:/var/lib/openldap/openldap-data/
      - ../docker/local_seed.ldif:/local_seed.ldif
