name: Deploy to all environments

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize, closed]

jobs:
  deploy:
    uses: ./.github/workflows/openldap-deploy-environment-reusable.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: dev
            image_tag: 0.80.0
          - environment: test
            image_tag: 0.80.0
    with:
      environment: ${{ matrix.environment }}
      image_tag: ${{ matrix.image_tag }}
    secrets: inherit
